/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmCustomersRouteImport } from './routes/crm.customers'
import { Route as CrmOrdersRouteImport } from './routes/crm.orders'
import { Route as CrmPlannerRouteImport } from './routes/crm.planner'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryItemsRouteImport } from './routes/inventory.items'
import { Route as InventoryTrackingRouteImport } from './routes/inventory.tracking'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as VendorCatalogRouteImport } from './routes/vendor.catalog'
import { Route as VendorCustomersRouteImport } from './routes/vendor.customers'
import { Route as VendorInboxRouteImport } from './routes/vendor.inbox'
import { Route as VendorReportsRouteImport } from './routes/vendor.reports'
import { Route as InventoryOrdersNewRouteImport } from './routes/inventory.orders.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCustomersRoute = CrmCustomersRouteImport.update({
  id: '/crm/customers',
  path: '/crm/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmOrdersRoute = CrmOrdersRouteImport.update({
  id: '/crm/orders',
  path: '/crm/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPlannerRoute = CrmPlannerRouteImport.update({
  id: '/crm/planner',
  path: '/crm/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/inventory/items',
  path: '/inventory/items',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryTrackingRoute = InventoryTrackingRouteImport.update({
  id: '/inventory/tracking',
  path: '/inventory/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorCatalogRoute = VendorCatalogRouteImport.update({
  id: '/vendor/catalog',
  path: '/vendor/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorCustomersRoute = VendorCustomersRouteImport.update({
  id: '/vendor/customers',
  path: '/vendor/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorInboxRoute = VendorInboxRouteImport.update({
  id: '/vendor/inbox',
  path: '/vendor/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorReportsRoute = VendorReportsRouteImport.update({
  id: '/vendor/reports',
  path: '/vendor/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryOrdersNewRoute = InventoryOrdersNewRouteImport.update({
  id: '/inventory/orders/new',
  path: '/inventory/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/crm/orders': typeof CrmOrdersRoute
  '/crm/planner': typeof CrmPlannerRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/tracking': typeof InventoryTrackingRoute
  '/vendor/catalog': typeof VendorCatalogRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/inbox': typeof VendorInboxRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/crm/': typeof CrmIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/inventory/orders/new': typeof InventoryOrdersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/crm/orders': typeof CrmOrdersRoute
  '/crm/planner': typeof CrmPlannerRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/tracking': typeof InventoryTrackingRoute
  '/vendor/catalog': typeof VendorCatalogRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/inbox': typeof VendorInboxRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/crm': typeof CrmIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/inventory/orders/new': typeof InventoryOrdersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/crm/orders': typeof CrmOrdersRoute
  '/crm/planner': typeof CrmPlannerRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/tracking': typeof InventoryTrackingRoute
  '/vendor/catalog': typeof VendorCatalogRoute
  '/vendor/customers': typeof VendorCustomersRoute
  '/vendor/inbox': typeof VendorInboxRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/crm/': typeof CrmIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/inventory/orders/new': typeof InventoryOrdersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm/customers'
    | '/crm/orders'
    | '/crm/planner'
    | '/inventory/items'
    | '/inventory/tracking'
    | '/vendor/catalog'
    | '/vendor/customers'
    | '/vendor/inbox'
    | '/vendor/reports'
    | '/crm/'
    | '/inventory/'
    | '/vendor/'
    | '/inventory/orders/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm/customers'
    | '/crm/orders'
    | '/crm/planner'
    | '/inventory/items'
    | '/inventory/tracking'
    | '/vendor/catalog'
    | '/vendor/customers'
    | '/vendor/inbox'
    | '/vendor/reports'
    | '/crm'
    | '/inventory'
    | '/vendor'
    | '/inventory/orders/new'
  id:
    | '__root__'
    | '/'
    | '/crm/customers'
    | '/crm/orders'
    | '/crm/planner'
    | '/inventory/items'
    | '/inventory/tracking'
    | '/vendor/catalog'
    | '/vendor/customers'
    | '/vendor/inbox'
    | '/vendor/reports'
    | '/crm/'
    | '/inventory/'
    | '/vendor/'
    | '/inventory/orders/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmCustomersRoute: typeof CrmCustomersRoute
  CrmOrdersRoute: typeof CrmOrdersRoute
  CrmPlannerRoute: typeof CrmPlannerRoute
  InventoryItemsRoute: typeof InventoryItemsRoute
  InventoryTrackingRoute: typeof InventoryTrackingRoute
  VendorCatalogRoute: typeof VendorCatalogRoute
  VendorCustomersRoute: typeof VendorCustomersRoute
  VendorInboxRoute: typeof VendorInboxRoute
  VendorReportsRoute: typeof VendorReportsRoute
  CrmIndexRoute: typeof CrmIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  VendorIndexRoute: typeof VendorIndexRoute
  InventoryOrdersNewRoute: typeof InventoryOrdersNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/customers': {
      id: '/crm/customers'
      path: '/crm/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof CrmCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/orders': {
      id: '/crm/orders'
      path: '/crm/orders'
      fullPath: '/crm/orders'
      preLoaderRoute: typeof CrmOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/planner': {
      id: '/crm/planner'
      path: '/crm/planner'
      fullPath: '/crm/planner'
      preLoaderRoute: typeof CrmPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/tracking': {
      id: '/inventory/tracking'
      path: '/inventory/tracking'
      fullPath: '/inventory/tracking'
      preLoaderRoute: typeof InventoryTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/vendor'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/catalog': {
      id: '/vendor/catalog'
      path: '/vendor/catalog'
      fullPath: '/vendor/catalog'
      preLoaderRoute: typeof VendorCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/customers': {
      id: '/vendor/customers'
      path: '/vendor/customers'
      fullPath: '/vendor/customers'
      preLoaderRoute: typeof VendorCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/inbox': {
      id: '/vendor/inbox'
      path: '/vendor/inbox'
      fullPath: '/vendor/inbox'
      preLoaderRoute: typeof VendorInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/reports': {
      id: '/vendor/reports'
      path: '/vendor/reports'
      fullPath: '/vendor/reports'
      preLoaderRoute: typeof VendorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/orders/new': {
      id: '/inventory/orders/new'
      path: '/inventory/orders/new'
      fullPath: '/inventory/orders/new'
      preLoaderRoute: typeof InventoryOrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmCustomersRoute: CrmCustomersRoute,
  CrmOrdersRoute: CrmOrdersRoute,
  CrmPlannerRoute: CrmPlannerRoute,
  InventoryItemsRoute: InventoryItemsRoute,
  InventoryTrackingRoute: InventoryTrackingRoute,
  VendorCatalogRoute: VendorCatalogRoute,
  VendorCustomersRoute: VendorCustomersRoute,
  VendorInboxRoute: VendorInboxRoute,
  VendorReportsRoute: VendorReportsRoute,
  CrmIndexRoute: CrmIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  VendorIndexRoute: VendorIndexRoute,
  InventoryOrdersNewRoute: InventoryOrdersNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
